### ISSUE TITLE
Integer values for X axis

### ISSUE THREAD

**Issue by andresriancho** [tammoippen/plotille#11]
First of all let me thank you for this tool. I've been using it to graph a lot of things lately, and it rocks!

Something that I've noticed in many of my graphs is that the X axis values quickly become unreadable. An example of a graph I'm seeing now:

```
0.00000   178.77778 357.55556 536.33333 715.11111 893.88889 1072.666671251.444441430.222221609.00000
```

![x](https://user-images.githubusercontent.com/865200/35982535-d40fc820-0cce-11e8-8240-7764b047e22a.png)

I was wondering if it would be possible to tell plotille to just print the integer values for the X axis (without the decimal part) and set a min spacing (2 spaces maybe?) between the values.

**Comment by tammoippen** [comment]
Hi @andresriancho ,

Thank you! I am happy that it is useful for you 😊 . Regarding the issue: it looks like you are not using the latest version. I ran into the same displaying issues and made some changes in [v3.2](https://pypi.python.org/pypi/plotille/3.2) that should keep labels in their 8-9 characters. Please try updating and see if that fixes the issue?

BTW: It looks like you are plotting timestamps (vs ... something else ;) ). In v3.2 it should be possible to directly give the `datetime` objects as X values.

**Comment by andresriancho** [comment]
Awesome! Upgrading fixed 50% of my problem: now I can read the values :+1: 

What about only displaying the integer part of the number in the X axis?

**Comment by tammoippen** [comment]
Right now, there are no plans to only show integer parts, or have an option for this... anyway, with the last update, you can supply formatters to a figure, that will render all labels (also the Y-axis), e.g.:

```python
from plotille import *
import random

def _num_formatter(val, chars, delta, left=False):
    align = '<' if left else ''
    return '{:{}{}d}'.format(int(val), align, chars)

fig = Figure()
fig.width = 30
fig.height = 15
fig.register_label_formatter(float, _num_formatter)
fig.register_label_formatter(int, _num_formatter)
fig.plot(list(range(100)), [random.randint(0, 20) for _i in range(100)])
print(fig.show())
```

![screen shot 2018-02-13 at 09 23 40](https://user-images.githubusercontent.com/4425925/36139906-a0b45c3c-109f-11e8-801c-c0c17f208a5f.png)

**Comment by andresriancho** [comment]
Lovely, you rock!

![screenshot from 2018-02-13 11-33-44](https://user-images.githubusercontent.com/865200/36154949-c7bd9020-10b1-11e8-8096-a1082f517d87.png)

**Comment by tammoippen** [comment]
😊 Thx.

**Comment by andresriancho** [comment]
Just in case you were wondering, your tool is being used to graph the results of parsing https://github.com/andresriancho/w3af scan log files:

https://github.com/andresriancho/w3af/blob/80b3cc71ea501e21ead9077d5b03f23a5247a3e6/w3af/core/controllers/profiling/scan_log_analysis.py

That tool generates nice output which allows me to better understand what w3af is doing internally, and how to improve it.

**Comment by tammoippen** [comment]
Wow! 👍  You got another ⭐️! I will definitely look into that project.😄

Since you actually plot `datetime`s (as `timestamp` deltas), have you tried to insert them directly? Replacing [the line 179](https://github.com/andresriancho/w3af/blob/80b3cc71ea501e21ead9077d5b03f23a5247a3e6/w3af/core/controllers/profiling/scan_log_analysis.py#L179) by:

```python
error_rate_timestamps = [datetime.datetime.fromtimestamp(ts) for ts in error_rate_timestamps]
```

and line 198 with:

```python
fig.set_x_limits(min_=datetime.datetime.fromtimestamp(first_timestamp), max_=datetime.datetime.fromtimestamp(last_timestamp))
```

Depending on the delta (aka `spent_epoch`) this will plot the actual time (or day and time).

**Comment by andresriancho** [comment]
Applied the changes you recommended to see how the output looked and got an exception:
```
  File "/home/caveman/tools/virtualenvs/w3af/local/lib/python2.7/site-packages/plotille/_figure.py", line 258, in show
    self.background, self.color_mode)
  File "/home/caveman/tools/virtualenvs/w3af/local/lib/python2.7/site-packages/plotille/_canvas.py", line 68, in __init__
    assert isinstance(xmin, (int, float))
AssertionError
```

The modified code:
```python
def show_extended_urllib_error_rate(scan):
    error_rate = []
    error_rate_timestamps = []

    for line in scan:
        match = EXTENDED_URLLIB_ERRORS_RE.search(line)
        if match:
            error_rate.append(int(match.group(1)))
            error_rate_timestamps.append(get_line_epoch(line))

    first_timestamp = get_first_timestamp(scan)
    last_timestamp = get_last_timestamp(scan)
    spent_epoch = last_timestamp - first_timestamp
    #error_rate_timestamps = [ts - first_timestamp for ts in error_rate_timestamps]
    error_rate_timestamps = [datetime.datetime.fromtimestamp(ts) for ts in error_rate_timestamps]

    if not error_rate:
        print('No error rate information found')
        return

    print('Extended URL library error rate')
    print('    Error rate exceeded 10%%: %s' % (max(error_rate) > 10,))
    print('    Error rate exceeded 20%%: %s' % (max(error_rate) > 10,))
    print('')

    fig = plotille.Figure()
    fig.width = 90
    fig.height = 20
    #fig.register_label_formatter(float, _num_formatter)
    #fig.register_label_formatter(int, _num_formatter)
    fig.y_label = 'Error rate'
    fig.x_label = 'Time'
    fig.color_mode = 'byte'
    fig.set_x_limits(min_=datetime.datetime.fromtimestamp(first_timestamp),
                     max_=datetime.datetime.fromtimestamp(last_timestamp))
    fig.set_y_limits(min_=0, max_=max(error_rate) * 1.1)

    fig.plot(error_rate_timestamps,
             error_rate,
             label='Error rate')

    print(fig.show())
    print('')
    print('')
```

I actually like the way the X axis looks like without the proposed change. I can see seconds since the beginning of the scan, which is easier to understand than a date / hour.

**Comment by tammoippen** [comment]
Thank you for the catch! The project is still young and I am happy for every feedback 😁.
