### ISSUE TITLE
Histogram Y axis integer values

### ISSUE THREAD

**Issue by andresriancho** [tammoippen/plotille#12]
![y](https://user-images.githubusercontent.com/865200/35982682-28b8b012-0ccf-11e8-8a7f-27ee2e877df4.png)

AFAIK it doesn't make sense to print the decimal part of the Y axis values when drawing a histogram.

Also, when printing some of these graphs the Y axis is not a straight line.

**Comment by tammoippen** [comment]
Hi @andresriancho ,

Same as #11: please try to update plotille to v3.2. 

The `Figure` does not differentiate whether this is a plot or a histogram when plotting the axis - and I would like to keep it that way, as it makes things easier... regardless of that, v3.2 should improve the Y label formatting. Please have a look and see, if that fixes the issue.

BTW: Have you tried [`plotille.hist`](https://github.com/tammoippen/plotille#hist)? This gives more information about the buckets and the counts are `int` (to the right).

**Comment by andresriancho** [comment]
plotille.hist is actually much better for showing the data, thanks!

**Comment by avijitbis7000-ui** [comment]
### _Tool
_
