### ISSUE TITLE
Not getting the graph as required

### ISSUE THREAD

**Issue by pradeepu1995** [tammoippen/plotille#17]
Sir, I am searching for a library to draw graph in terminal and I found this library and used this, but the output is not getting as required. Please help out. 

The code I used (which is given in readme of your library)
```
import  plotille
import numpy as np 
X = np.sort(np.random.normal(size=1000))
fig = plotille.Figure() 
fig.width = 60 
fig.height = 30 
fig.set_x_limits(min_=-3, max_=3)
fig.set_y_limits(min_=-1, max_=1) 
fig.color_mode = 'byte' 
fig.plot([-0.5, 1], [-1, 1], lc=25, label='First line')
fig.scatter(X, np.sin(X), lc=100, label='sin')  
fig.plot(X, (X+2)**2 , lc=200, label='square')
print(fig.show(legend=True))
```

The output what I got

![](https://i.imgur.com/liCbL7a.png)

The actual output (shown in read me)

![](https://i.imgur.com/1WaZd68.jpg)

Why I am getting the extra `braille dots`? Please help me. Waiting for your replay.

Thank you.

**Comment by pradeepu1995** [comment]
Thank you for your quick response,

OS - arch Linux (`4.12`)

Python version `3.6.2`

plotille version `3.4`

Terminal - xfce4-terminal (`0.8.6`) 

Font - Monospace Regular

**Comment by pradeepu1995** [comment]
Ok sir. I will try and let you know if that worked for me.

**Comment by tammoippen** [comment]
If the error persists, please reopen the issue and detail the errors.

**Comment by slhck** [comment]
I also thought this was a font issue. I am getting this kind of result with `Source Code Pro` in VS Code's integrated terminal:

<img width="764" alt="image" src="https://github.com/tammoippen/plotille/assets/582444/efb514a9-3994-4fc9-be8e-f5c9374c5e83">

And this with `SF Mono` (the default for macOS) in Terminal.app:

<img width="869" alt="image" src="https://github.com/tammoippen/plotille/assets/582444/9004f4fe-d22b-4586-b89c-6bf196d3b51f">

Changing the font to SF Mono in VS Code still shows the dots, so it is likely **not** the font itself, but some other settings.
Both terminals have `xterm-256color` as `$TERM`.

**Comment by tammoippen** [comment]
Hi @slhck,

this still looks like a font issue in the VS Code terminal. Did you set the terminal font to SF Mono or the editor font - they can be set independently:

- "terminal.integrated.fontFamily"
- "editor.fontFamily"

**Comment by slhck** [comment]
Hm, I've definitely set it to other fonts to check, as I can see the font change when I change the setting, and it still looks like this, also trying with `Consolas` or `Menlo`:

<img width="754" alt="image" src="https://github.com/tammoippen/plotille/assets/582444/d75d85fb-9248-496c-9cf0-d9ee56cb005c">

It's also not the color theme, as far as I can tell, as I can't find any VS Code theme that doesn't render it like this.
