### ISSUE TITLE
Heatmap

### ISSUE THREAD

**Issue by tammoippen** [tammoippen/plotille#2]

**Comment by bhattg** [comment]
Hello, any updates on this? Thanks for the amazing library!

**Comment by tammoippen** [comment]
Hi @bhattg ,

Thank you for the nice words. Actually, I recently had some ideas and started implementing then. Have a look at #44 which will be the basis for heatmaps.

Images will be available as monochrome images on the basis of braille dots, and as color images on the basis of rgb background colors.

Here are some examples:

<img width="561" alt="Screenshot 2021-08-28 at 21 43 58" src="https://user-images.githubusercontent.com/4425925/131229210-49492248-03bb-4d60-8f79-e8ca338aca54.png">
<img width="567" alt="Screenshot 2021-08-28 at 21 41 41" src="https://user-images.githubusercontent.com/4425925/131229220-ce87a8de-5327-4a4f-9468-c3694f7d2eb6.png">
<img width="563" alt="Screenshot 2021-08-28 at 21 42 22" src="https://user-images.githubusercontent.com/4425925/131229223-33e06650-50d8-4d46-9146-ccc51a7f92aa.png">

**Comment by bhattg** [comment]
This sounds amazing. Thanks!

**Comment by tammoippen** [comment]
Fixed with #44
