### ISSUE TITLE
[feature request] Provide a CLI

### ISSUE THREAD

**Issue by Lucas-C** [tammoippen/plotille#29]
Could you please provide a command-line entry point ?

Other similar libs (`termgraph`, `bashplotlib`, `diagram`) provide one, and it is very handy to draw a scatterplot / histogram in terminal from comma or space separated data in `stdin`.

**Comment by tammoippen** [comment]
Hallo @Lucas-C ,

This sounds like a nice project, which I will most definitely put on my agenda... but I think I do not want it in the `plotille` repository. A separate repo / project will do fine.

**Comment by Lucas-C** [comment]
IMHO a separate repo for a scripts that would probably be less than 50 lines is not necessary.
I could submit a PR if you change your mind, but else feel free to close this issue.

**Comment by tammoippen** [comment]
No CLI in this project.
