### ISSUE TITLE
has someone ever integrated this on a curses-like interface ?

### ISSUE THREAD

**Issue by chromafunk** [tammoippen/plotille#40]
Is this even possible ? I was thinking on making a terminal UI based on curses to plot real time, maybe someone has already tried ?

**Comment by tammoippen** [comment]
Hi @chromafunk ,

I think this should be perfectly possible. 

Basically, plotille just uses ASCII codes for colors. And `Figure.show(…)` returns a `str` you can print with whatever function you like. 

Would be great, if you keep me posted on your project (i am just curious) and i am happy to help, if you encounter problem. 

Best, Tammo

**Comment by chromafunk** [comment]
yeah, that's why I came here ... basically I love this lib  and I want to build a curses interface with it, I have set up a test with it, and it seems that for some reason, curses can't render braille characters properly ( this is in the same term where I am running plotille )

I have tried to force using the locale as some online posts suggest but I'm getting this : 

https://ibb.co/qWZ3fxx

Do you know why this happens and how to fix it ? I believe that once this is fixed, it would be possible and then I will finish it. Another option that I am working on is to make it with notcurses instead of with curses, but this requires more work on the source code ( somebody is already working on it ) let me know !

**Comment by tammoippen** [comment]
Hi, looks like the ansii escape codes are escaped somehow (all the ^[[ gibberish). Apparently ncurses does not like these, as it uses the codes itself. Maybe this helps: https://stackoverflow.com/questions/30189434/how-to-display-pre-colored-string-with-curses

(I am on the phone and cannot check, sry)

**Comment by chromafunk** [comment]
gotcha ! yeah someone is building a parser for notcurses and I'm just going to jump in and help with it. I'll let you know when it's finished
