### ISSUE TITLE
Feature request: Network graph

### ISSUE THREAD

**Issue by antoniovazquezblanco** [tammoippen/plotille#56]
It would be lovely to be able to plot simple network graphs.
https://en.wikipedia.org/wiki/Network_theory
Chart size may be an issue but for small plots nodes may be constructed using icons or small colored unicode characters that may be explained in a legend...

**Comment by tammoippen** [comment]
Hi @antoniovazquezblanco ,

please have a look at the new example in #58. As there are many ways to represent a network graph, i do not want to make a specific api for them. Though, simple network graphs are already possible using the Canvas class with the methods `point` and `line`.

> nodes may be constructed using icons or small colored unicode characters 

Use the `marker` parameter of the point method - you can put any unicode character there. 

Best, Tammo
