### ISSUE TITLE
Time series plotting

### ISSUE THREAD

**Issue by svenstaro** [tammoippen/plotille#6]
I would like to plot a list of datetimes but the problem is that I currently have to convert them to unix timestamps because this library does not support straight printing of datetimes. Now the problem with that is that timestamps tend to become quite large (and are also hard to read for humans). Can you implement time series plotting of lists of datetimes?

**Comment by tammoippen** [comment]
Hi @svenstaro,

Thanks for your interest. What kind of time series plotting do you have in mind? Something like having `X` a list of `Date` or `Datetime` instances and `Y` numbers? E.g. :

![](http://support.minitab.com/en-us/minitab-express/1/tsplot_calls_multiple_ys_consecutive_4col.xml_Graph_cmd2o1.png)

Or only having a list of dates for histograms? E.g.:

![](https://i.stack.imgur.com/exn5E.png)

Or more like spike trains:

![](https://praneethnamburi.files.wordpress.com/2015/02/02_raster_baselineandstim.png)

It would be good, if you could elaborate a bit and/or give examples.

BTW: Human readable dates can also be quite large, eg [RFC 3339](https://tools.ietf.org/html/rfc3339): `2018-01-03T19:41:01+00:00` if you want timestamp resolution X-labels. And two of them for `hist` ranges. Do you have suggestions, how to display dates?

**Comment by svenstaro** [comment]
I had the first plot in mind but the histogram would also be neat to have. I don't care so much about spike trains. It would be convenient to be able to format the labels in a user-specified way.

**Comment by tammoippen** [comment]
This sounds doable and interesting. I will look into this, when time permits;).
