### ISSUE TITLE
Remove the y axes min line from plot charts

### ISSUE THREAD

**Issue by brablc** [tammoippen/plotille#61]
Hello, I chose you cute library for visualisation of sar/sysstat data in the terminal. I have the basic charting working and will just add some interactivity to it: https://github.com/brablc/lazysar .

My minor concern is the minimum y line. My charts start mostly at zero and it creates a phantom line above the x axes. May be there is an easy solution to it?
![image](https://github.com/tammoippen/plotille/assets/841734/351487ab-8452-4fc8-b1b8-1eca274828c5)
Used command: `lazysar --ago=1 --height 30 --exclude=%iowait,%nice,%idle -- -i 300 -u`

**Comment by tammoippen** [comment]
Hi @brablc ,

What you are seeing is the origin at y=0. There is also an origin at x=0. You can deactivate the origin with

`figure.origin = False`

I hope this helps!

Best, Tammo

**Comment by brablc** [comment]
Perfect, thank you! Sorry to mix things up, byt is there any way:

- How to show the X label so that it does not shortens the chart?
- How to put legend ono ne line: `Legend: ... %user ... %system ... %steal`
- Anything else I missed to make chart even nicer?

![image](https://github.com/tammoippen/plotille/assets/841734/e9d56939-d57f-41a0-9f06-6af690cfba07)

**Comment by tammoippen** [comment]
> - How to show the X label so that it does not shortens the chart?

You mean the `(Time)` all the way to the right, right? You cannot right now. One solution would be to put it in the place of the last tick on the x-axis; or below the last tick (which would require a new line...). I think replacing the last tick is the nicer solution. 

> - How to put legend ono ne line: `Legend: ... %user ... %system ... %steal`

Not possible yet. Though, this should be an easy option. 

> 
> - Anything else I missed to make chart even nicer?

There is nothing coming to my mind right now - look already very nice 😉. 

I let you know, when i come around implementing the features.

**Comment by brablc** [comment]
Thanks - it looks nice I guess - check multipane examples on https://github.com/brablc/lazysar .
