### ISSUE TITLE
Allow users to provide label transformation functions

### ISSUE THREAD

**Issue by svenstaro** [tammoippen/plotille#7]
Imagine we have a plot and have x values that look like this: 100000000011000013551 or like this 130141414.0001401212401. We don't want to print them like this but we do want to provide these values to our graph. It would be cool to be able to pass in a transformation function that would be executed for each label to transform these values to, for instance, 1E20 + 13551 or maybe even more human readable formats such as "2h ago", "1h ago".

Currently, graphing big values with plotille will lead to completely unreadable labels next to the plot.

**Comment by tammoippen** [comment]
Fixed with #10. Closing.
